### ISSUE TITLE
Créer le module "user"

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_v4#12]
Etudier le module "user" existant dans ci_packbase_hmvc et l'intégrer à la nouvelle version ci_packbase_v4.

- Choisir une manière de gérer les sessions adaptée à ce qui est prévu par CI 4
- Choisir une manière de valider les formulaires adaptée à ce qui est prévu par CI 4
- Prévoir les scripts de création de la base de données dans le dossier "Database" du module et dans les sous-dossiers "Migrations" et "Seeds". Voir comment gérer ces fichiers dans CI 4
- De manière générale, adapter tout le module (modèles, contrôleurs, etc.) pour suivre les bonnes pratiques de CI 4

**Comment by DidierViret** [comment]
Pour la validation des données, j'aimerais qu'on teste la possibilité de créer les règles de validation dans les modèles. Il me semble que ce serait le plus efficace mais ça reste à tester et à confirmer.

**Comment by DidierViret** [comment]
Suite à notre discussion du jour, continuer à travailler sur les éléments suivants :
- Database, créer les fichiers "Migrations" et "Seeds" pour la création des tables et leur contenu
- Cosmétique du code, ajouter les cartouches d'en-tête, nettoyer le code, vérifier les commentaires de classes et fonctions
- Transférer le paramètre de niveau d'accès dans le BaseController à la place des routes

**Comment by maximeor** [comment]
Ce travail est terminé
