### ISSUE TITLE
Mise à jour vers Bootstrap 4.6

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_v4#16]
- Mettre à jour la feuille de style Bootstrap Orif (public/css/bootstrap.min.css) pour être compatible Bootstrap 4.6.
- Changer les liens CDN pour faire appel à la version 4.6 de Bootstrap (orif/common/Views/header.php).
- Vérifier le fonctionnement des différents modules.

**Comment by maximeor** [comment]
J'ai fait la mise à jour dans le header de "jquery,  popper, bootstrapjs, "
