### ISSUE TITLE
Mettre en place des tests unitaires pour les modules "common" et "user"

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_v4#19]
Voir quelles sont les solutions prévues dans CI 4 pour la mise en place de tests unitaires.
Tester les différentes possibilités et mettre en place des tests unitaires qui permettent de s'assurer du bon fonctionnement des modules "common" et "user".

La documentation officielle à ce sujet se trouve ici :
https://www.codeigniter.com/user_guide/testing/overview.html

**Comment by maximeor** [comment]
done:
-Tester les liens cdn jquery, popper, bootsrapjs (avc la classe CURLRequest de ci4)
-Tester les balises html head body (avc la classe CURLRequest de ci4)
in progress:
-Test sur l'affichage des action avec privilèges
