### ISSUE TITLE
Modèle générique

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_v4#2]
Étudier comment intégrer ou remplacer le modèle générique "MY_Model.php" qui était utilisé dans ci_packbase_hmvc

**Comment by BurkhalterY** [comment]
Le CRUD de base est prit en charge par CodeIgniter 4 ainsi que le soft_delete. Mais le soft_delete a maintenant besoin d'une date qui vaut NULL tant que l'enregistrement n'est pas supprimé.
Pour les relations entre plusieurs tables (fonction with() de l'ancien model), j'ai testé le plugin suivant :
https://packagist.org/packages/tatter/relations
Il crée un schemas de la base de donnée et génère automatiquement les relations. Mais je n'ai pas réussi à le faire marcher.
Je vais maintenant voir comment était fais l'ancien MY_Model pour voir s'il est possible d'en reprendre une partie.

**Comment by DidierViret** [comment]
Pour le moment nous utiliserons les fonctions de base de CI 4 pour récupérer les éléments liés, afin d'éviter de devoir installer une extension tierce.
