### ISSUE TITLE
Modularisation

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_v4#3]
Étudier les possibilités de reprendre les modules de ci_packbase_hmvc de manière à ce qu'il puissent être réutilisés dans plusieurs applications.
Dans la mesure du possible, utiliser les possibilités offertes de base dans CodeIgniter 4, sans projet complémentaire. Par exemple, voir les possibilités existantes avec les Namespaces.

**Comment by BurkhalterY** [comment]
Pour créer un module, il faut créer un nouveau sous-dossier à la racine du projet avec le nom Orif par exemple (pour les modules de l'Orif). Puis en créer un deuxième avec le nom du module (par exemple User). On peut ensuite recréer les dossiers nécessaire à l'intérieur (Controllers, Models, Views, etc...). Il faut préciser le namespace en haut du fichier. Par exemple : 
`namespace Orif\User\Controllers;`

Pour le premier module, il faudra également ajouter au fichier App/Config/Autoload.php l'entrée suivante dans le tableau $psr4 : 
`'Orif' => ROOTPATH.'Orif'`
